"""Editor chrome is separate from the editable SAFECheck catalogs."""

TEXTS = {
    "premium_icon": ("✨ Premium emoji", "✨ Premium emoji", "✨ Premium эмодзи"),
    "remove_icon": ("× Pašalinti ikoną", "× Remove icon", "× Удалить иконку"),
    "current_icon": ("Premium ikona: {id}", "Premium icon: {id}", "Premium иконка: {id}"),
    "no_icon": ("nenustatyta", "not set", "не задана"),
    "icon_prompt": (
        "Atsiųsk vieną tikrą Premium emoji iš Telegram emoji pasirinkimo arba jo skaitinį ID. Ikona bus rodoma prieš mygtuko tekstą šioje kalboje.\n\nBoto savininkui reikia Telegram Premium arba botui papildomo vardo iš Fragment.",
        "Send one genuine Premium emoji from Telegram's emoji picker, or its numeric ID. The icon will appear before this button's text in the selected language.\n\nThe bot's owner needs Telegram Premium, or the bot needs an additional username from Fragment.",
        "Отправьте один настоящий Premium эмодзи из меню Telegram или его числовой ID. Иконка появится перед текстом кнопки в выбранном языке.\n\nВладельцу бота нужен Telegram Premium либо боту — дополнительное имя с Fragment.",
    ),
    "icon_invalid": (
        "Atsiųsk vieną tikrą Premium emoji arba galiojantį jo ID. Paprastas tekstinis emoji šiai ikonai netinka.",
        "Send one genuine Premium emoji or its valid ID. A plain Unicode emoji cannot be used as this icon.",
        "Отправьте один настоящий Premium эмодзи или его действительный ID. Обычный текстовый эмодзи не подходит для этой иконки.",
    ),
    "icon_lookup_failed": (
        "Telegram emoji patikra nepavyko. Pasirinkimas nepakeistas; pabandyk atsiųsti dar kartą.",
        "Telegram could not verify the emoji. The selection is unchanged; try sending it again.",
        "Telegram не смог проверить эмодзи. Настройка не изменена; отправьте его ещё раз.",
    ),
    "premium_unavailable": (
        "Telegram atmetė Premium emoji; peržiūra parodyta be jo. Pasirinkimas išsaugotas. Patikrink, ar boto savininkas turi Telegram Premium, arba botas turi papildomą vardą iš Fragment.",
        "Telegram rejected the Premium emoji; this preview is shown without it. Your selection is saved. Check whether the bot's owner has Telegram Premium, or the bot has an additional username from Fragment.",
        "Telegram отклонил Premium эмодзи; просмотр показан без него. Настройка сохранена. Проверьте Telegram Premium у владельца бота либо дополнительное имя бота с Fragment.",
    ),
    "use_icon_picker": (
        "Premium ikoną priskirk per mygtuko „✨ Premium emoji“ nustatymą. Čia keičiamas mygtuko tekstas.",
        "Set the Premium icon through this button's “✨ Premium emoji” option. This field changes the button text.",
        "Назначьте Premium иконку через настройку «✨ Premium эмодзи». Здесь меняется текст кнопки.",
    ),
    "result": ("📑 Rezultato tekstai", "📑 Result texts", "📑 Тексты результата"),
    "result_preview": ("👀 Peržiūrėti rezultatą", "👀 Preview result", "👀 Просмотр результата"),
    "result_clear": ("Rezultatas · SCAM nėra", "Result · no SCAM", "Результат · нет SCAM"),
    "result_unknown": (
        "Rezultatas · ID nežinomas",
        "Result · unknown ID",
        "Результат · ID неизвестен",
    ),
    "result_scam": ("Rezultatas · SCAM", "Result · SCAM", "Результат · SCAM"),
    "result.p.profile_title": ("Rezultato antraštė", "Result heading", "Заголовок результата"),
    "result.p.profile_card": (
        "Reputacija ir REP skaičiai",
        "Reputation and REP counts",
        "Репутация и количество REP",
    ),
    "result.p.lookup_status": ("Statuso antraštė", "Status heading", "Заголовок статуса"),
    "result.p.lookup_clear_status": (
        "SCAM įrašų nerasta",
        "No SCAM record found",
        "Записей SCAM не найдено",
    ),
    "result.p.no_scam": (
        "Paaiškinimas · SCAM nėra",
        "Explanation · no SCAM",
        "Пояснение · нет SCAM",
    ),
    "result.p.lookup_identity_known": (
        "Susieta su Telegram ID",
        "Linked to Telegram ID",
        "Связано с Telegram ID",
    ),
    "result.p.unknown_identity": (
        "Tapatybė nepatvirtinta",
        "Identity not confirmed",
        "Личность не подтверждена",
    ),
    "result.p.warning": (
        "Patikimumo garantijos pastaba",
        "Reliability disclaimer",
        "Примечание о надёжности",
    ),
    "result.p.lookup_scam_status": (
        "SCAM įrašas rastas",
        "SCAM record found",
        "Запись SCAM найдена",
    ),
    "result.p.lookup_scam_description": ("SCAM paaiškinimas", "SCAM explanation", "Пояснение SCAM"),
    "result.p.lookup_reason": ("SCAM priežastis", "SCAM reason", "Причина SCAM"),
    "result.p.lookup_reference": ("SCAM įrašo numeris", "SCAM record number", "Номер записи SCAM"),
    "result.p.lookup_scam_date": ("SCAM įrašo data", "SCAM record date", "Дата записи SCAM"),
    "result.p.scam_admin_confirmation": (
        "Administracijos patvirtinimas",
        "Administrator confirmation",
        "Подтверждение администрации",
    ),
    "result.p.lookup_caution": ("SCAM atsargumo pastaba", "SCAM caution", "Предостережение SCAM"),
    "result.p.trusted_status": ("TRUSTED statusas", "TRUSTED status", "Статус TRUSTED"),
    "result.p.lookup_trusted_manual": (
        "TRUSTED paaiškinimas",
        "TRUSTED explanation",
        "Пояснение TRUSTED",
    ),
    "result.p.lookup_trusted_date": (
        "TRUSTED atnaujinimo data",
        "TRUSTED update date",
        "Дата обновления TRUSTED",
    ),
    "result.p.lookup_trusted_top": (
        "TOP 10 · TRUSTED statusas",
        "TOP 10 · TRUSTED status",
        "TOP 10 · статус TRUSTED",
    ),
    "result.p.lookup_trusted_top_description": (
        "TOP 10 · TRUSTED paaiškinimas",
        "TOP 10 · TRUSTED explanation",
        "TOP 10 · пояснение TRUSTED",
    ),
    "result.p.lookup_trusted_role": ("TRUSTED pagal rolę", "Role-based TRUSTED", "TRUSTED по роли"),
    "result.p.role": ("Rolės antraštė", "Role heading", "Заголовок роли"),
    "result.p.role_founder": ("Įkūrėjo rolė", "Founder role", "Роль основателя"),
    "result.p.role_moderator": ("Moderatoriaus rolė", "Moderator role", "Роль модератора"),
    "result.p.lookup_username_match": (
        "Username sutapimo statusas",
        "Username match status",
        "Статус совпадения имени",
    ),
    "result.p.lookup_username_match_description": (
        "Username sutapimo paaiškinimas",
        "Username match explanation",
        "Пояснение совпадения имени",
    ),
    "editors": ("👥 Redaktoriai", "👥 Editors", "👥 Редакторы"),
    "add_editor": ("➕ Pridėti pagal ID", "➕ Add by ID", "➕ Добавить по ID"),
    "access_list": (
        "👥 Redagavimo prieiga · {count}\n\n👑 Administratorius · ✏️ Redaktorius\n\n{rows}",
        "👥 Editing access · {count}\n\n👑 Administrator · ✏️ Editor\n\n{rows}",
        "👥 Доступ к редактированию · {count}\n\n👑 Администратор · ✏️ Редактор\n\n{rows}",
    ),
    "editor_prompt": (
        "Atsiųsk žmogaus Telegram ID, pvz. 8425927753. Jis galės redaguoti testinį dizainą.",
        "Send the person's Telegram ID, e.g. 8425927753. They will be able to edit the test design.",
        "Отправьте Telegram ID пользователя, например 8425927753. Он сможет редактировать тестовый дизайн.",
    ),
    "editor_invalid": (
        "Įvesk tik teigiamą skaitinį Telegram ID, be @ ar kitų žodžių.",
        "Enter a positive numeric Telegram ID, without @ or other words.",
        "Введите положительный числовой Telegram ID, без @ и других слов.",
    ),
    "editor_added": (
        "✓ ID {id} suteikta redagavimo prieiga. Gali atidaryti botą ir spausti Start.",
        "✓ ID {id} can now edit. They can open the bot and press Start.",
        "✓ ID {id} получил доступ к редактированию. Можно открыть бота и нажать Start.",
    ),
    "editor_exists": (
        "ID {id} jau turi redagavimo prieigą.",
        "ID {id} already has editing access.",
        "ID {id} уже имеет доступ к редактированию.",
    ),
    "manage_denied": (
        "Pridėti redaktorius gali tik testinio boto administratorius.",
        "Only a test bot administrator can add editors.",
        "Добавлять редакторов может только администратор тестового бота.",
    ),
    "too_long": (
        "Šio ekrano tekstas viršija Telegram 4096 simbolių ribą. Sutrumpink pasirinktus tekstus.",
        "This screen exceeds Telegram's 4096-character limit. Shorten the selected texts.",
        "Текст экрана превышает лимит Telegram в 4096 символов. Сократите выбранные тексты.",
    ),
    "title": ("🛡 CRIMSON SAFECHECK™ · UI STUDIO",) * 3,
    "intro": (
        "Keisk dizainą ir peržiūrėk jį čia. Visi vartotojų duomenys peržiūrose yra pavyzdiniai.",
        "Edit the design and preview it here. All user data in previews are samples.",
        "Меняйте дизайн и смотрите результат здесь. Все данные пользователей — примеры.",
    ),
    "buttons": ("🔘 Mygtukai", "🔘 Buttons", "🔘 Кнопки"),
    "texts": ("📝 Tekstai", "📝 Texts", "📝 Тексты"),
    "order": ("↕️ Mygtukų tvarka", "↕️ Button layout", "↕️ Порядок кнопок"),
    "preview": ("👀 Peržiūra", "👀 Preview", "👀 Просмотр"),
    "language": ("🌐 Kalba", "🌐 Language", "🌐 Язык"),
    "export": ("📦 Atsisiųsti dizainą", "📦 Download design", "📦 Скачать дизайн"),
    "back": ("◀ Atgal", "◀ Back", "◀ Назад"),
    "editor": ("◀ UI redaktorius", "◀ UI editor", "◀ Редактор UI"),
    "search": ("🔍 Rasti", "🔍 Search", "🔍 Найти"),
    "search_prompt": (
        "Parašyk žodį iš ieškomo teksto arba mygtuko.",
        "Type a word from the text or button you want to find.",
        "Введите слово из нужного текста или кнопки.",
    ),
    "empty": (
        "Nieko nerasta. Pabandyk kitą žodį.",
        "No matches. Try another word.",
        "Ничего не найдено. Попробуйте другое слово.",
    ),
    "edit": ("✏️ Keisti", "✏️ Edit", "✏️ Изменить"),
    "reset": ("↻ Grąžinti numatytą", "↻ Restore default", "↻ Вернуть исходный"),
    "reset_layout": ("↻ Grąžinti tvarką", "↻ Restore layout", "↻ Вернуть порядок"),
    "current": ("Dabartinė reikšmė", "Current value", "Текущее значение"),
    "prompt": (
        "Atsiųsk naują tekstą. Emoji gali kopijuoti tiesiai į tekstą.",
        "Send the new text. You can paste emoji directly into it.",
        "Отправьте новый текст. Эмодзи можно вставить прямо в него.",
    ),
    "placeholders": (
        "Išsaugok šiuos kintamuosius: {fields}",
        "Keep these placeholders: {fields}",
        "Сохраните эти переменные: {fields}",
    ),
    "saved": (
        "✓ Išsaugota testiniame dizaine.",
        "✓ Saved in the test design.",
        "✓ Сохранено в тестовом дизайне.",
    ),
    "conflict": (
        "Šis tekstas jau pakeistas. Atidaryk jį iš naujo.",
        "This text changed while you were editing. Open it again.",
        "Этот текст уже изменён. Откройте его заново.",
    ),
    "invalid": (
        "Tekstas netinkamas. Mygtukas: iki 64 simbolių, viena eilutė. Tekstas: iki 3500. Išsaugok kintamuosius ir patikrink HTML žymas.",
        "Invalid text. Button: up to 64 characters, one line. Text: up to 3500. Keep placeholders and check HTML tags.",
        "Неверный текст. Кнопка: до 64 символов, одна строка. Текст: до 3500. Сохраните переменные и проверьте HTML.",
    ),
    "layout_prompt": (
        "Parašyk visų mygtukų numerius norima tvarka. Viena teksto eilutė = viena mygtukų eilutė; iki 3 mygtukų eilutėje. Kiekvieną numerį naudok tik kartą.\n\nDabartinis išdėstymas:\n{rows}",
        "Send all button numbers in the desired order. One line = one button row; up to 3 per row. Use every number exactly once.\n\nCurrent layout:\n{rows}",
        "Отправьте все номера кнопок в нужном порядке. Одна строка = ряд кнопок, до 3 в ряду. Каждый номер ровно один раз.\n\nТекущий порядок:\n{rows}",
    ),
    "layout_invalid": (
        "Patikrink numerius: visi turi būti panaudoti po vieną, iki 3 vienoje eilutėje.",
        "Check the numbers: use each exactly once, up to 3 per row.",
        "Проверьте номера: каждый ровно один раз, до 3 в строке.",
    ),
    "home": ("Pagrindinis meniu", "Main menu", "Главное меню"),
    "home_user": ("Pagrindinis · vartotojas", "Main · user", "Главное · пользователь"),
    "home_admin": (
        "Pagrindinis · administratorius",
        "Main · administrator",
        "Главное · администратор",
    ),
    "admin": ("Administravimas", "Administration", "Администрирование"),
    "info": ("Informacija", "Information", "Информация"),
    "scam": ("SCAM · ID žinomas", "SCAM · known ID", "SCAM · ID известен"),
    "scam_unknown": ("SCAM · ID nežinomas", "SCAM · unknown ID", "SCAM · ID неизвестен"),
    "trusted": ("TRUSTED",) * 3,
    "profile": ("Profilis / tikrinimas", "Profile / lookup", "Профиль / проверка"),
    "demo": (
        "Tai tik dizaino peržiūra. Veiksmas nevykdomas.",
        "This is a design preview. No action is performed.",
        "Это просмотр дизайна. Действие не выполняется.",
    ),
    "denied": (
        "Šis testinis botas prieinamas tik administratoriams ir redaktoriams privačiai.",
        "This test bot is available only to administrators and editors in private.",
        "Тестовый бот доступен только администраторам и редакторам в личном чате.",
    ),
    "stale": (
        "Atidaryk redaktorių iš naujo per /ui.",
        "Reopen the editor with /ui.",
        "Откройте редактор заново: /ui.",
    ),
    "error": (
        "Išsaugoti ar parodyti nepavyko. Pabandyk dar kartą.",
        "Could not save or display. Please try again.",
        "Не удалось сохранить или показать. Попробуйте снова.",
    ),
}


def text(key: str, lang: str = "lt", **values) -> str:
    return TEXTS[key][{"lt": 0, "en": 1, "ru": 2}.get(lang, 0)].format(**values)
