"""Initial relational schema, immutable snapshot."""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_index(
        "uq_unknown_username",
        "users",
        ["username"],
        unique=True,
        sqlite_where=sa.text("telegram_id IS NULL"),
        postgresql_where=sa.text("telegram_id IS NULL"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_locks",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_rep", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_report", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED')"),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_index(op.f("ix_reports_target_id"), "reports", ["target_id"], unique=False)
    op.create_table(
        "reputation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("giver_user_id", sa.Integer(), nullable=False),
        sa.Column("receiver_user_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("giver_user_id != receiver_user_id"),
        sa.CheckConstraint("value IN (-1, 1)"),
        sa.ForeignKeyConstraint(
            ["giver_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("giver_user_id", "receiver_user_id", name="uq_rep_pair"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_index(
        op.f("ix_reputation_events_giver_user_id"),
        "reputation_events",
        ["giver_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reputation_events_receiver_user_id"),
        "reputation_events",
        ["receiver_user_id"],
        unique=False,
    )
    op.create_table(
        "username_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_username_history_user_id"), "username_history", ["user_id"], unique=False
    )
    op.create_table(
        "moderation_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("moderator_id", sa.BigInteger(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id"),
    )
    op.create_table(
        "report_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("file_id", sa.String(length=512), nullable=False),
        sa.Column("caption", sa.String(length=512), nullable=True),
        sa.CheckConstraint("kind IN ('photo','document','message')"),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_evidence_report_id"), "report_evidence", ["report_id"], unique=False
    )
    op.create_table(
        "scam_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("username_snapshot", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("moderator_id", sa.BigInteger(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_by", sa.BigInteger(), nullable=True),
        sa.Column("removal_reason", sa.Text(), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','REMOVED')"),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scam_records_target_id"), "scam_records", ["target_id"], unique=False)
    op.create_index(
        "uq_active_scam",
        "scam_records",
        ["target_id"],
        unique=True,
        sqlite_where=sa.text("status='ACTIVE'"),
        postgresql_where=sa.text("status='ACTIVE'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_scam",
        table_name="scam_records",
        sqlite_where=sa.text("status='ACTIVE'"),
        postgresql_where=sa.text("status='ACTIVE'"),
    )
    op.drop_index(op.f("ix_scam_records_target_id"), table_name="scam_records")
    op.drop_table("scam_records")
    op.drop_index(op.f("ix_report_evidence_report_id"), table_name="report_evidence")
    op.drop_table("report_evidence")
    op.drop_table("moderation_actions")
    op.drop_index(op.f("ix_username_history_user_id"), table_name="username_history")
    op.drop_table("username_history")
    op.drop_index(op.f("ix_reputation_events_receiver_user_id"), table_name="reputation_events")
    op.drop_index(op.f("ix_reputation_events_giver_user_id"), table_name="reputation_events")
    op.drop_table("reputation_events")
    op.drop_index(op.f("ix_reports_target_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("operation_locks")
    op.drop_table("audit_events")
    op.drop_index(
        "uq_unknown_username",
        table_name="users",
        sqlite_where=sa.text("telegram_id IS NULL"),
        postgresql_where=sa.text("telegram_id IS NULL"),
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
