"""Moderated reputation and append-only administrative ledger."""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002_identity_lock"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reputation_adjustments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("positive_delta", sa.Integer(), nullable=False),
        sa.Column("negative_delta", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("operation IN ('ADJUST','RESET')"),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_index(
        op.f("ix_reputation_adjustments_target_id"),
        "reputation_adjustments",
        ["target_id"],
        unique=False,
    )
    op.create_table(
        "reputation_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("giver_user_id", sa.Integer(), nullable=False),
        sa.Column("receiver_user_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("moderator_id", sa.BigInteger(), nullable=True),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED')"),
        sa.CheckConstraint("giver_user_id != receiver_user_id"),
        sa.CheckConstraint("value IN (-1,1)"),
        sa.ForeignKeyConstraint(
            ["giver_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("giver_user_id", "receiver_user_id", name="uq_rep_request_pair"),
        sa.UniqueConstraint("reference"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_index(
        op.f("ix_reputation_requests_giver_user_id"),
        "reputation_requests",
        ["giver_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reputation_requests_receiver_user_id"),
        "reputation_requests",
        ["receiver_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reputation_requests_status"), "reputation_requests", ["status"], unique=False
    )
    op.create_table(
        "top_visibility",
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("target_id"),
    )
    op.create_table(
        "top_visibility_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("top_visibility_actions")
    op.drop_table("top_visibility")
    op.drop_index(op.f("ix_reputation_requests_status"), table_name="reputation_requests")
    op.drop_index(op.f("ix_reputation_requests_receiver_user_id"), table_name="reputation_requests")
    op.drop_index(op.f("ix_reputation_requests_giver_user_id"), table_name="reputation_requests")
    op.drop_table("reputation_requests")
    op.drop_index(op.f("ix_reputation_adjustments_target_id"), table_name="reputation_adjustments")
    op.drop_table("reputation_adjustments")
    # ### end Alembic commands ###
