"""Managed groups and durable moderation/recovery outboxes."""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managed_groups",
        sa.Column("chat_type", sa.String(length=16), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("can_restrict_members", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "private_contacts",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "observed_members",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["managed_groups.chat_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id", "telegram_id"),
    )
    op.create_table(
        "recovery_campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("invite_url", sa.Text(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["managed_groups.chat_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_table(
        "recovery_subscriptions",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["managed_groups.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["private_contacts.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id", "telegram_id"),
    )
    op.create_table(
        "recovery_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_type", sa.String(length=64), nullable=True),
        sa.CheckConstraint("status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED','OBSOLETE')"),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["recovery_campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "telegram_id", name="uq_recovery_recipient"),
    )
    op.create_index(
        op.f("ix_recovery_deliveries_status"), "recovery_deliveries", ["status"], unique=False
    )
    op.create_table(
        "ban_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("scam_record_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_type", sa.String(length=64), nullable=True),
        sa.CheckConstraint("status IN ('PENDING','PROCESSING','SUCCEEDED','FAILED','OBSOLETE')"),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["managed_groups.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["scam_record_id"],
            ["scam_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "telegram_id", "scam_record_id", name="uq_ban_activation"),
    )
    op.create_index(op.f("ix_ban_actions_chat_id"), "ban_actions", ["chat_id"], unique=False)
    op.create_index(op.f("ix_ban_actions_status"), "ban_actions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ban_actions_status"), table_name="ban_actions")
    op.drop_index(op.f("ix_ban_actions_chat_id"), table_name="ban_actions")
    op.drop_table("ban_actions")
    op.drop_index(op.f("ix_recovery_deliveries_status"), table_name="recovery_deliveries")
    op.drop_table("recovery_deliveries")
    op.drop_table("recovery_subscriptions")
    op.drop_table("recovery_campaigns")
    op.drop_table("observed_members")
    op.drop_table("private_contacts")
    op.drop_table("managed_groups")
    # ### end Alembic commands ###
